- flags/1x1/ua.svg
- flags/4x3/ua.svg
Formally, it should look like
According to "DSTU 4512:2006" mentioned on [wiki](https://en.wikipedia.org/wiki/Flag_of_Ukraine).
So it's a combination of "strong azure" and yellow.
> Ukrainian flag colors are standard compliant

- flags/1x1/in.svg
Clearly an accident.
We should maybe have a validation test so this doesn't happen again.
> India: Text data outside of root node

- flags/1x1/ng.svg
- flags/4x3/ng.svg
> fixed colors for Nigeria (NG) flag

- flags/1x1/mz.svg
- flags/4x3/mz.svg
> fixed Mozambique (MZ) flag colors

- flags/1x1/pl.svg
- flags/4x3/pl.svg
https://pl.wikipedia.org/wiki/Flaga_Polski#Odcie.C5.84_bieli_na_polskiej_fladze
> Updated Polish flag colors according to Wikipedia

- flags/4x3/lv.svg
Correct colors to real
https://lv.wikipedia.org/wiki/Latvijas_karogs
> Correct flag colors

- flags/1x1/pl.svg
- flags/4x3/pl.svg
The white is now white, see: https://en.wikipedia.org/wiki/File:Flag_of_Poland.svg
> Fix colors of Poland Flag (PL)

- flags/1x1/no.svg
- flags/4x3/no.svg
This corrects the colours in the Norwegian flag to be closer to the official colours.
> Fix the colours in the Norwegian flag

- flags/1x1/lt.svg
- flags/4x3/lt.svg
> Flag of Lithuania

- flags/1x1/dk.svg
- flags/4x3/dk.svg
> Danish flag colors

- flags/1x1/nl.svg
- flags/4x3/nl.svg
Much simpler SVG reducing filesize
> simplified SVG for 1x1 and 4x3 nl.svg

- flags/1x1/gf.svg
- flags/4x3/gf.svg
> Update current flag of French Guiana

- flags/1x1/nc.svg
- flags/4x3/nc.svg
> Flag of New Caledonia

- flags/1x1/bh.svg
- flags/4x3/bh.svg
> Flag of BH

- flags/1x1/se.svg
- flags/4x3/se.svg
Colors and proportions are the same.
> Slim down Sweden flag

- flags/1x1/je.svg
- flags/4x3/je.svg
fixes #680
It seems like the flag itself already had the right aspect ratio and only the page was wrong. I used inkscape to resize the image to the content and then applied those changes to the original file.
> fix je.svg (4x3)

- sass/_flag-icons-base.scss
> Don't use math in sass

- package.json
> build: ignore some files on publish to npm

- flags/1x1/kr.svg
- flags/4x3/kr.svg
- index.html
> Fix KR flag

- flags/1x1/mg.svg
- flags/4x3/mg.svg
> Fix Madagascar

- flags/1x1/ua.svg
- flags/4x3/ua.svg
Source: ДСТУ 4512:2006 - National standard of Ukraine.
> Fix colours of Ukrainian flag

- flags/1x1/hn.svg
- flags/4x3/hn.svg
> Fix HN flag

- CHANGELOG.md
- flags/1x1/ar.svg
- flags/4x3/ar.svg
Fixes #964 
Taken from Wikipedia and then SVGO.
> Fix Argentina

- flags/1x1/am.svg
- flags/4x3/am.svg
> Fix colors of Armenian flag (AM)

- flags/1x1/vn.svg
- flags/4x3/vn.svg
> Fix flag of Vietnam

- flags/1x1/cn.svg
- flags/4x3/cn.svg
> Fix colors of China

- flags/1x1/ch.svg
- flags/4x3/ch.svg
> Fix flag of Switzerland

- flags/1x1/ar.svg
- flags/1x1/cefta.svg
- flags/1x1/dg.svg
- flags/1x1/gu.svg
- flags/1x1/io.svg
- flags/1x1/ky.svg
- flags/1x1/mm.svg
- flags/1x1/sm.svg
- flags/1x1/tc.svg
- flags/4x3/ar.svg
- flags/4x3/cefta.svg
- flags/4x3/dg.svg
- flags/4x3/gu.svg
- flags/4x3/io.svg
- flags/4x3/ky.svg
- flags/4x3/mm.svg
- flags/4x3/sm.svg
- flags/4x3/tc.svg
> Fix flag of Myanmar

- flags/1x1/gr.svg
- flags/4x3/gr.svg
> Fix colors of Greece

- flags/1x1/cu.svg
- flags/4x3/cu.svg
Compare the colors with the colors used on Wikipedia: https://en.wikipedia.org/wiki/Flag_of_Cuba
> Fix colors of Cuban flag

- svgo.config.js
As a result of the discussion in #1086, here's the updated version of the PR.
Closes #1045
Closes #1078
> feat: enable prefixIds svgo plugin

- CHANGELOG.md
- flags/1x1/td.svg
- flags/4x3/td.svg
> Fix Flag of Chad

- flags/1x1/mq.svg
- flags/4x3/mq.svg
> Update flag of Martinique

- .github/workflows/flags.yml
https://github.com/actions/checkout
> Use: actions/checkout@v4

- maven.sh
- package.json
> Publishing to maven central via 'yarn maven'

- README.md
Updated the CDN Version from 7.0.0 to 7.2.3 in README.md
> Updated Version in README

- flags/1x1/sy.svg
- flags/4x3/sy.svg
Replace the old Syrian flag with the new flag that has been adopted by the new Syrian government.
> the new syrian flag
